language: php

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.2
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1

matrix:
  include:
    - php: '7.1'
      env: WITH_COVERAGE=true
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ "$WITH_COVERAGE" != "true" && -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - travis_retry composer install --prefer-dist

script:
  - if [[ "$WITH_COVERAGE" != "true" ]]; then composer test; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then composer test-with-coverage; fi

after_script:
  # Install helper scripts
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then export PATH=$HOME/.composer/vendor/bin:$PATH; fi

  # Upload coverage report
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-scrutinizer; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-codecov; fi
