language: php

dist: trusty

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - COMPOSER_DEPENDENCIES="highest"
    - COMPOSER_DEPENDENCIES=""

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" && "$COMPOSER_DEPENDENCIES" == "" ]]; then WITH_COVERAGE=true; fi

  # Disable xDebug to speed up the build unless test coverage is needed
  - if [[ "$WITH_COVERAGE" != "true" && $(phpenv version-name) != "nightly" ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ "$COMPOSER_DEPENDENCIES" == "highest" ]]; then travis_retry composer update --prefer-dist; fi
  - if [[ "$COMPOSER_DEPENDENCIES" == "" ]]; then travis_retry composer install --prefer-dist; fi

script:
  - if [[ "$WITH_COVERAGE" != "true" ]]; then composer test; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then composer test-with-coverage; fi

after_script:
  # Install helper scripts
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then export PATH=$HOME/.composer/vendor/bin:$PATH; fi

  # Upload coverage report
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-scrutinizer; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then travis_retry tnw-upload-coverage-to-codecov; fi
